### ISSUE TITLE
Possibility to change iManufacturer, iProduct, etc

### ISSUE THREAD

**Issue by Sloox** [SpacehuhnTech/USBNova#3]
Hi,
Is there a possibility to change 
iManufacturer,
iProduct

Came across a situation where it was blocked by looking at these fields.

**Comment by spacehuhn** [comment]
Just published a new release which supports manufacturer, serial, and product descriptor by editing the preferences file

**Comment by Sloox** [comment]
@spacehuhn great thanks!
