### ISSUE TITLE
Critical bug: GUI and WINDOWS commands on Windows 10 22H2 no longer work

### ISSUE THREAD

**Issue by DevelopingEntitiesWithFuntations** [SpacehuhnTech/USBNova#4]
Hello,

I tried setting up the hello world example on the newest 1.12 firmware and it just types out the letters and doesn't open run on any of the two machines I tested.

Cheers

**Comment by spacehuhn** [comment]
That's odd. And it works again if you flash the v1.1.1 firmware?

**Comment by DevelopingEntitiesWithFuntations** [comment]
Backflashing is fully supported? 

I'd rather not flash it, never change a running system as they say. I received the USB Nova with a v1.1.2 firmware already on it.

**Comment by LopeKinz** [comment]
yes you can backflash the usbnova since its still an arduino

**Comment by spacehuhn** [comment]
Just published a new version 1.2.0 as well. I recommend you try that one.

**Comment by DevelopingEntitiesWithFuntations** [comment]
@spacehuhn just flashed it. Seems like it still doesn't work :( The only setting that I changed in the settings is that I set my locale to de in the preferences.json...

A friend of mine seems to have gotten some functionality by using Ducky Script, but I want to use this kind of code...

**Comment by spacehuhn** [comment]
Can you share your script?

**Comment by DevelopingEntitiesWithFuntations** [comment]
Gladly. It's the following:
```
# USB Nova (v1.1.2->1.2.0)
DEFAULTDELAY 200
DELAY 2000
GUI R
DELAY 2000
STRING notepad
ENTER
STRING Hello World!

```

**Comment by spacehuhn** [comment]
```
# USB Nova (v1.1.2->1.2.0)
DEFAULTDELAY 200
DELAY 2000
GUI r
DELAY 2000
STRING notepad
ENTER
DELAY 2000
STRING Hello World!
```

I changed `R` to `r` and added another delay. Does this work for you?

**Comment by LopeKinz** [comment]
> ```
> # USB Nova (v1.1.2->1.2.0)
> DEFAULTDELAY 200
> DELAY 2000
> GUI r
> DELAY 2000
> STRING notepad
> ENTER
> DELAY 2000
> STRING Hello World!
> ```
> 
> I changed `R` to `r` and added another delay. Does this work for you?

tested it and it works for me with the "r" instead of "R".

**Comment by spacehuhn** [comment]
Awesome. I updated the docs already :) Sorry for the problems. 
With `GUI R`, it's like pressing windows shift and r at the same time, because the R is upper case. It does something different (or nothing at all) than just pressing windows and r.

**Comment by DevelopingEntitiesWithFuntations** [comment]
Changing R to r solved the issue!
